## Separators
# These are grammatical separators, mostly to separate sentences and phrases.

[!]
category = "separator"
gloss = "exclamation"
grammar = ["punct"]
type = "punctuation"

[,]
category = "separator"
gloss = "comma"
grammar = ["punct"]
type = "punctuation"

[.]
category = "separator"
gloss = "period"
grammar = ["punct"]
type = "punctuation"

[:]
category = "separator"
gloss = "colon"
grammar = ["punct"]
type = "punctuation"

[?]
category = "separator"
gloss = "question"
grammar = ["punct"]
type = "punctuation"

## Words, sorted alphabetically

[a]
gloss = "ah"
grammar = ["interj"]

[akesi]
category = "animal"
gloss = "reptile"
grammar = ["n"]

[ala]
gloss = "no"
grammar = ["mod","n","interj"]

[ali]
gloss = "all"
grammar = ["n","mod"]

[anpa]
gloss = "under"
grammar = ["n","mod"]

[ante]
gloss = "different"
grammar = ["n","mod","conj","vt"]

[anu]
category = "separator"
gloss = "or"
grammar = ["conj"]

[awen]
gloss = "remain"
grammar = ["vi","vt","mod"]

[e]
category = "separator"
gloss = "object marker"
grammar = ["sep"]

[en]
category = "separator"
gloss = "and"
grammar = ["conj"]

[esun]
gloss = "shop"
grammar = ["n"]

[ijo]
gloss = "thing"
grammar = ["n","mod","vt"]

[ike]
gloss = "evil"
grammar = ["mod","interj","n","vt","vi"]

[ilo]
gloss = "tool"
grammar = ["n"]

[insa]
gloss = "inside"
grammar = ["n","mod"]

[jaki]
gloss = "dirty"
grammar = ["mod","n","vt","interj"]

[jan]
category = "animal"
gloss = "person"
grammar = ["n","mod","vt"]

[jelo]
category = "color"
gloss = "yellow"
grammar = ["mod"]

[jo]
gloss = "have"
grammar = ["vt","n"]

[kala]
category = "animal"
gloss = "fish"
grammar = ["n"]

[kalama]
gloss = "sound"
grammar = ["n","vi","vt"]

[kama]
gloss = "come"
grammar = ["vi","n","mod","vt"]

[kasi]
gloss = "plant"
grammar = ["n"]

[ken]
gloss = "possible"
grammar = ["vi","n","vt"]

[kepeken]
gloss = "use"
grammar = ["vt","prep"]

[kili]
gloss = "fruit"
grammar = ["n"]

[kin]
gloss = "also"
grammar = ["mod"]

[kiwen]
gloss = "rock"
grammar = ["mod","n"]

[ko]
gloss = "squishy"
grammar = ["n"]

[kon]
gloss = "soul"
grammar = ["n","mod"]

[kule]
gloss = "color"
grammar = ["n","mod","vt"]

[kulupu]
gloss = "group"
grammar = ["n","mod"]

[kute]
gloss = "listen"
grammar = ["vt","mod"]

[la]
category = "separator"
gloss = "in context"
grammar = ["sep"]

[lape]
gloss = "rest"
grammar = ["n","vi","mod"]

[laso]
category = "color"
gloss = "blue/green"
grammar = ["mod"]

[lawa]
gloss = "head"
grammar = ["n","mod","vt"]

[len]
gloss = "cloth"
grammar = ["n"]

[lete]
gloss = "cold"
grammar = ["n","mod","vt"]

[li]
category = "separator"
gloss = "is"
grammar = ["sep"]

[lili]
gloss = "small"
grammar = ["mod","vt"]

[linja]
gloss = "string"
grammar = ["n"]

[lipu]
gloss = "paper"
grammar = ["n"]

[loje]
category = "color"
gloss = "red"
grammar = ["mod"]

[lon]
gloss = "located"
grammar = ["prep","vi"]

[luka]
gloss = "hand"
grammar = ["n"]

[lukin]
gloss = "see"
grammar = ["vt","vi","mod"]

[lupa]
gloss = "hole"
grammar = ["n"]

[ma]
gloss = "land"
grammar = ["n"]

[mama]
category = "animal"
gloss = "parent"
grammar = ["n","mod"]

[mani]
gloss = "money"
grammar = ["n"]

[meli]
category = "animal"
gloss = "female"
grammar = ["n","mod"]

[mi]
gloss = "I/we"
grammar = ["n","mod"]

[mije]
category = "animal"
gloss = "male"
grammar = ["n","mod"]

[moku]
gloss = "food"
grammar = ["n","vt"]

[moli]
gloss = "death"
grammar = ["n","vi","vt","mod"]

[monsi]
gloss = "back"
grammar = ["n","mod"]

[mu]
gloss = "moo!"
grammar = ["interj"]

[mun]
gloss = "moon"
grammar = ["n","mod"]

[musi]
gloss = "play"
grammar = ["n","mod","vi","vt"]

[mute]
gloss = "many"
grammar = ["mod","n","vt"]

[namako]
gloss = "extra"
grammar = ["n","mod"]

[nanpa]
gloss = "number"
grammar = ["n"]

[nasa]
gloss = "crazy"
grammar = ["mod","vt"]

[nasin]
gloss = "manner"
grammar = ["n"]

[nena]
gloss = "bump"
grammar = ["n"]

[ni]
gloss = "this"
grammar = ["mod"]

[nimi]
gloss = "name"
grammar = ["n"]

[noka]
gloss = "leg"
grammar = ["n"]

[o]
gloss = "imperative"
grammar = ["sep","interj"]

[oko]
gloss = "eye"
grammar = ["n"]

[olin]
gloss = "love"
grammar = ["n","mod","vt"]

[ona]
gloss = "he/she/it"
grammar = ["n","mod"]

[open]
gloss = "open"
grammar = ["vt"]

[pakala]
gloss = "destroy"
grammar = ["n","vt","vi","interj"]

[pali]
gloss = "make"
grammar = ["n","mod","vt","vi"]

[palisa]
gloss = "rod"
grammar = ["n"]

[pan]
gloss = "grain"
grammar = ["n"]

[pana]
gloss = "give"
grammar = ["vt","n"]

[pi]
category = "separator"
gloss = "of"
grammar = ["sep"]

[pilin]
gloss = "feel"
grammar = ["n","vi","vt"]

[pimeja]
category = "color"
gloss = "black"
grammar = ["mod","n","vt"]

[pini]
gloss = "end"
grammar = ["n","mod","vt"]

[pipi]
category = "animal"
gloss = "insect"
grammar = ["n"]

[poka]
gloss = "side"
grammar = ["n","mod","prep"]

[poki]
gloss = "box"
grammar = ["n"]

[pona]
gloss = "good"
grammar = ["n","mod","interj","vt"]

[pu]
gloss = "toki ponist"
grammar = ["n","mod","vi"]

[sama]
gloss = "similar"
grammar = ["mod","prep"]

[seli]
gloss = "warm"
grammar = ["n","mod","vt"]

[selo]
gloss = "surface"
grammar = ["n"]

[seme]
gloss = "what"
grammar = ["n","mod","vi"]

[sewi]
gloss = "superior"
grammar = ["n","mod"]

[sijelo]
gloss = "body"
grammar = ["n"]

[sike]
gloss = "circle"
grammar = ["n","mod"]

[sin]
gloss = "new"
grammar = ["mod","vt"]

[sina]
gloss = "you"
grammar = ["n","mod"]

[sinpin]
gloss = "front"
grammar = ["n"]

[sitelen]
gloss = "draw"
grammar = ["n","vt"]

[sona]
gloss = "wisdom"
grammar = ["n","vt","vi"]

[soweli]
category = "animal"
gloss = "mammal"
grammar = ["n"]

[suli]
gloss = "big"
grammar = ["mod","vt","n"]

[suno]
gloss = "light"
grammar = ["n"]

[supa]
gloss = "table"
grammar = ["n"]

[suwi]
gloss = "sweet"
grammar = ["n","mod","vt"]

[tan]
gloss = "because"
grammar = ["prep","n"]

[taso]
gloss = "only"
grammar = ["mod","conj"]

[tawa]
gloss = "move"
grammar = ["prep","vi","n","mod","vt"]

[telo]
gloss = "liquid"
grammar = ["n","vt"]

[tenpo]
gloss = "time"
grammar = ["n"]

[toki]
gloss = "talking"
grammar = ["n","mod","vt","vi","interj"]

[tomo]
gloss = "house"
grammar = ["n","mod"]

[tu]
gloss = "two"
grammar = ["mod","n","vt"]

[unpa]
gloss = "sex"
grammar = ["n","mod","vt","vi"]

[uta]
gloss = "mouth"
grammar = ["n","mod"]

[utala]
gloss = "attack"
grammar = ["n","vt"]

[walo]
category = "color"
gloss = "white"
grammar = ["mod","n"]

[wan]
gloss = "one"
grammar = ["mod","n","vt"]

[waso]
category = "animal"
gloss = "bird"
grammar = ["n"]

[wawa]
gloss = "power"
grammar = ["n","mod","vt"]

[weka]
gloss = "away"
grammar = ["mod","n","vt"]

[wile]
gloss = "need"
grammar = ["vt","n","mod"]
